version: "3.4"

services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '33066:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'pharmacy'
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}" ]
      retries: 3
      timeout: 5s

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: pharmacy
    driver: bridge
